### PR TITLE
fix crash with hackustry

### PR DESCRIPTION
**Pull request by QmelZ**

### CODE REVIEW

**Comment by QmelZ** [comment]
(also your code suck but i don't feel like fixing it rn)

**Comment by sk7725** [comment]
Make sure your code works before making a PR. (also, make sure it works without hackustry too.)
Also, can you also fix the crash in BE too?

**Comment by QmelZ** [comment]
> Make sure your code works

it does work

> can you also fix the crash in BE

maybe

**Comment by sk7725** [comment]
> it does work

was I a dingus and made something unrequired a `const`?

**Comment by sk7725** [comment]
oh importPackage
also its used in all other files too, is there no need to fix it in other files?

**Comment by QmelZ** [comment]
wait what i only saw it in that one file

**Pull request merged**
